[theme]
base="dark"  # Tema oscuro
primaryColor="#006400"  # Verde oscuro para los elementos principales
backgroundColor="#121212"  # Fondo oscuro para el cuerpo
secondaryBackgroundColor="#f5f5dc"  # Fondo crema claro para la barra lateral
textColor="#ffffff"  # Texto blanco para un buen contraste
