[theme]
base="dark"
primaryColor="#003366"  # Azul oscuro
backgroundColor="#001f33"  # Fondo en azul oscuro más suave
secondaryBackgroundColor="#003366"  # Fondo de la barra lateral azul oscuro
textColor="#ffffff"  # Color de texto blanco
