[theme]
base="light"  # Tema claro
primaryColor="#28a745"  # Verde
backgroundColor="#ffffff"  # Blanco para el fondo
secondaryBackgroundColor="#f8f9fa"  # Fondo de la barra lateral blanco suave
textColor="#212529"  # Texto oscuro para buen contraste
